

    </body>
    <! –– Javascript includes skal være her. ––>

<script>
            function toHome(){

            document.getElementById("home").submit();
            }
            function toShop(){

             document.getElementById("shop").submit();
             }
             function toSignup(){

             document.getElementById("signup").submit();
             }

             function toLogin(){

             document.getElementById("login").submit();
             }
             function toKurv(){

             document.getElementById("kurv").submit();
             }


             function toBrugere(){
             document.getElementById("Brugere").submit();
             }
              function toOrdre(){
               document.getElementById("Ordre").submit();
                }



        </script>


</html>