<html>
    <head>

        <title>Cupcake projekt</title>
        <link rel="stylesheet" type="text/css" href="stylesheets/header.css">
        <link rel="stylesheet" type="text/css" href="stylesheets/Styles.css">

    </head>
    <body>
       <img src="resources/olskercupcakes.png">

       <div class="navigation-bar">
           <a href="#top" class="navigation-item">Home</a>
           <a href="#top" class="navigation-item">Shop</a>
           <a href="#top" class="navigation-item">Login</a>
           <a href="#top" class="navigation-item">Sign-up</a>
           <a id="basket" class="navigation-item"> <img  src="basket.png"> </a>
      </div>
    </body>

